inherit_from: ../.rubocop.yml

# Avoid warning "Possibly useless use of == in void context"
# for `should ==`
Void:
  Enabled: false

# Sometimes I want to indicate that “This is a hash” explicitly with #and_return.
BracesAroundHashParameters:
  Enabled: false
